---
name: "GitHub Super Linter"

on:
  schedule:
    - cron: "0 12 * * *"
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-wkflw-linter:
    permissions:
      contents: read
      packages: read
      statuses: write
    name: "Rewkflw: GitHub Super Linter"
    uses: pandemonium1986/.github/.github/workflows/rewkflw-linter.yml@main
    secrets:
      github-token: inherit
