---
name: "GitHub Super Linter"

on:
  schedule:
    - cron: "0 12 * * *"
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    name: "Lint Code Base"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: super-linter/super-linter/slim@v5
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
